// Builds the small companions of every product photo; the photos themselves are never touched.
//
//   src/assets/looks/thumbs/<name>.webp  3× the 96×127 strip size, so the strip never has to
//                                        download and shrink a full 1080px photo
//   src/data/placeholders.ts             a tiny blurred preview of each photo, inlined in the JS,
//                                        shown behind it until the real one has painted
//
// Run `npm run images` after adding or replacing a photo, and commit the output.
import { mkdir, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const root = path.resolve(import.meta.dirname, '..');
const looksDir = path.join(root, 'src/assets/looks');
const thumbsDir = path.join(looksDir, 'thumbs');
const sources = [
  ...(await readdir(looksDir)).filter((f) => f.endsWith('.webp')).map((f) => path.join(looksDir, f)),
  path.join(root, 'public/media/hero-poster.webp'),
].sort();

await mkdir(thumbsDir, { recursive: true });

const placeholders = {};
for (const file of sources) {
  const name = path.basename(file, '.webp');
  await sharp(file)
    .resize({ width: 320, kernel: 'lanczos3' })
    .webp({ quality: 90, smartSubsample: true, effort: 6 })
    .toFile(path.join(thumbsDir, `${name}.webp`));

  const tiny = await sharp(file).resize({ width: 24 }).blur(1).webp({ quality: 60 }).toBuffer();
  placeholders[name] = `data:image/webp;base64,${tiny.toString('base64')}`;
  console.log(`${name}: thumb + ${tiny.length} B placeholder`);
}

await writeFile(
  path.join(root, 'src/data/placeholders.ts'),
  `// Generated by scripts/optimize-images.mjs — do not edit.\n` +
    `export const placeholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)};\n`,
);
